# .github/workflows/ci-cd.yml

name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0

      - name: Restore dependencies
        run: dotnet restore

      - name: Build application
        run: dotnet build --configuration Release

      - name: Run tests
        run: dotnet test --no-restore --verbosity normal

      - name: Publish application
        run: dotnet publish --configuration Release --output ./publish/

      # Add your deployment steps here
      # ...

